### ISSUE TITLE
change function is not working

### ISSUE THREAD

**Issue by jamalwill325** [Code-With-Coffee/CustomSegmentedControl#6]
The change function is not triggering when I switch between buttons.

**Comment by faganello60** [comment]
Can you share your code?
In my example is working fine

**Comment by jamalwill325** [comment]
Line 465 isn’t triggering when I switch cells

**Comment by jamalwill325** [comment]
This is my initializer

**Comment by jamalwill325** [comment]
Any Uodate? If not I will have to use something else

**Comment by faganello60** [comment]
Hello,
I testes de example code in my xcode and works fine!
Verify if you do the same thing in your code.
I can't see your init.

**Comment by jamalwill325** [comment]
Turns out I needed to add the delegate to my view controller. Thanks for the quick response!
